from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
import os


class ReportGenerator:

    @staticmethod
    def generate(
        filename,
        summary,
        kpis,
        insights,
        recommendations
    ):

        os.makedirs("reports", exist_ok=True)

        path = os.path.join("reports", filename)

        styles = getSampleStyleSheet()

        doc = SimpleDocTemplate(path)

        elements = []

        elements.append(
            Paragraph("<b><font size=22>DA GENIUS</font></b>", styles["Title"])
        )

        elements.append(
            Paragraph("Executive Analytics Report", styles["Heading2"])
        )

        elements.append(Spacer(1, 0.3 * inch))

        elements.append(
            Paragraph("<b>Dataset Summary</b>", styles["Heading2"])
        )

        table_data = [["Metric", "Value"]]

        for k, v in summary.items():
            table_data.append([k, str(v)])

        table = Table(table_data)

        table.setStyle(

            TableStyle(

                [

                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0E7490")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 10)

                ]

            )

        )

        elements.append(table)

        elements.append(Spacer(1, 0.3 * inch))

        elements.append(
            Paragraph("<b>Key Performance Indicators</b>", styles["Heading2"])
        )

        for k, v in kpis.items():

            elements.append(

                Paragraph(f"<b>{k}</b> : {v}", styles["BodyText"])

            )

        elements.append(Spacer(1, 0.2 * inch))

        elements.append(

            Paragraph("<b>Business Insights</b>", styles["Heading2"])

        )

        for i in insights:

            elements.append(

                Paragraph(f"• {i}", styles["BodyText"])

            )

        elements.append(Spacer(1, 0.2 * inch))

        elements.append(

            Paragraph("<b>Recommendations</b>", styles["Heading2"])

        )

        for r in recommendations:

            elements.append(

                Paragraph(f"• {r}", styles["BodyText"])

            )

        elements.append(Spacer(1, 0.2 * inch))

        elements.append(

            Paragraph("<b>Generated by DA GENIUS</b>", styles["Heading2"])

        )

        doc.build(elements)

        return path